import { readFile, writeFile, rename, unlink } from 'node:fs/promises';
import { fileURLToPath, pathToFileURL } from 'node:url';
import path from 'node:path';
import { randomUUID } from 'node:crypto';
import { config } from '../dist/lib/config.js';
import { inspectToken, makeRpc } from './lib/token-inspection.mjs';

export function tokenModule(metadata) {
  // JSON serialization keeps contract metadata inert, including quotes/newlines.
  return '// Verified public token metadata. Generated by scripts/configure-token.mjs.\n'
    + 'export const accessToken = Object.freeze(' + JSON.stringify(metadata, null, 2) + ');\n';
}

export async function saveToken(metadata, target = new URL('../dist/lib/access-token.js', import.meta.url)) {
  const destination = fileURLToPath(target);
  const temporary = destination + '.' + randomUUID() + '.tmp';
  // Read first so a missing/mislocated destination never silently creates a new config.
  await readFile(destination, 'utf8');
  try {
    await writeFile(temporary, tokenModule(metadata), { flag: 'wx' });
    await rename(temporary, destination);
  } finally {
    await unlink(temporary).catch(error => { if (error.code !== 'ENOENT') throw error; });
  }
}

export async function main(args = process.argv.slice(2)) {
  if (args.length === 0 || args.includes('--help')) {
    console.log('Usage: node scripts/configure-token.mjs <token-contract-address> [--write]');
    console.log('Default: read-only verification. --write updates local access-token.js after every check succeeds.');
    console.log('Optional APEX_RPC_URL selects an HTTPS RPC provider. No private key is used.');
    return;
  }
  if (args.length > 2 || (args.length === 2 && args[1] !== '--write') || args[0].startsWith('--')) {
    throw Error('Expected one token contract address, optionally followed by --write.');
  }
  const metadata = await inspectToken({
    address: args[0],
    rpc: makeRpc(process.env.APEX_RPC_URL || config.network.rpcUrls[0]),
    chainId: Number(BigInt(config.network.chainId)),
    required: config.required,
  });
  console.log(JSON.stringify({
    ...metadata,
    requiredTokens: config.required.toString(),
    explorer: config.network.blockExplorerUrls[0] + '/address/' + metadata.address,
    ponsPage: 'https://www.ponsfamily.com/launchpad/' + metadata.address,
    ponsProvenance: 'Not asserted by ERC-20 checks; verify the official launch page or factory event.',
  }, null, 2));
  if (args.includes('--write')) {
    await saveToken(metadata);
    console.log('Local access token updated. Review the exact address, then deploy this release. Registration is still closed.');
  } else {
    console.log('Inspection only. No token was activated and no files were changed.');
  }
}

if (process.argv[1] && import.meta.url === pathToFileURL(path.resolve(process.argv[1])).href) {
  main().catch(error => { console.error(error.message); process.exitCode = 1; });
}
